### ISSUE TITLE
Cocoapods Installation failure

### ISSUE THREAD

**Issue by NerdGr8** [ArtSabintsev/Guitar#8] opened 2017-03-09 07:10 UTC
Tried installing the library through cocoapods and it fails with the following error 

`[!] Unable to find a specification for `Guitar``

**Comment by ArtSabintsev** [comment] 2017-03-09 07:30
Hmm, can't reproduce that.

- What version of CocoaPods are you using?
- What version of Guitar are you trying to install?

This what worked for me `pod 'Guitar'`.

**Comment by ArtSabintsev** [comment] 2017-03-09 16:06
Going to close this issue, but feel free to comment, and I'll follow up.

**Closed as completed** 2017-03-09 16:06 UTC
